CREATE TABLE Categories
(
    CategoryId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),

    CategoryTitle NVARCHAR(200) NOT NULL,

    Slug NVARCHAR(200) NOT NULL UNIQUE,

    CreatedAt DATETIME2 DEFAULT SYSDATETIME(),

    UpdatedAt DATETIME2 DEFAULT SYSDATETIME(),

    AdminId UNIQUEIDENTIFIER NOT NULL,

    IsActive BIT DEFAULT 1,


    CONSTRAINT FK_Categories_admin
    FOREIGN KEY (AdminId)
    REFERENCES admin(id)
);